version: '3'

services:
  frontend:
    image: myapp-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    image: myapp-backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: myapp-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
